### PR TITLE
Story/geco 79

### PR DESCRIPTION
**Pull request by abhikrish503501**

### CODE REVIEW

**Comment by jdamerow** [comment]
please resolve conflicts.

**Comment by abhikrish503501** [comment]
Resolved merge conflicts.

**Comment by jdamerow** [comment]
Is there a reason you're not using a jquery plugin for this (e.g. https://esimakin.github.io/twbs-pagination/)?

**Comment by abhikrish503501** [comment]
Its easy to shift from digg style pagination to any other styles with this piece of code, which is not with case of a plugin. This piece of code has almost all the elements needed for the pagination, if we want to change it in the future.

**Comment by jdamerow** [comment]
At least the one I linked let's you define which classes should be used for each element, so changing that shouldn't be a big deal if we ever move a way from bootstrap. And it's actually easier to maintain (only one place to change a class name not 8). I understand why you made that choice but in this case, it's probably more maintainable using a plugin (less code, easier to maintain).

**Pull request merged**
